### ISSUE TITLE
Q: Does this support Bash 4.3 as well?

### ISSUE THREAD

**Issue by hintron** [pallets-eco/click-bash4.2-completion#2]
Is this package specific to Bash 4.2, or does it cover Bash 4.3 as well? The readme seems to imply it only works with Bash 4.2. Thanks!

**Comment by coreegor** [comment]
Hello!
I think it will work on Bash 4.3 but I can't test it right now. I would appreciate it if you can check it out

**Comment by hintron** [comment]
It does seem to work for Bash 4.3! Thanks so much!

It's not a big deal, but with my custom autocomplete function:

```python3
    def get_scripts(_ctx, _args, incomplete):
        """Populate scripts"""
        scripts = list_scripts()
        return [script for script in scripts if incomplete in script]
```
I am no longer able to match the middle parts of the file like I used to. It used to be like this:

    $ myprog max<TAB>
    maxlit.sh setmax.sh imax.sh

Now it only does:

    $ myprog max<TAB>
    maxlit.sh

I'm guessing the 'file" autocomplete code is what makes it that way:
```bash
    if [[ $type == 'dir' ]]; then
        COMPREPLY=()
        compopt -o dirnames
    elif [[ $type == 'file' ]]; then
        COMPREPLY=()
        compopt -o default
    elif [[ $type == 'plain' ]]; then
        COMPREPLY+=($value)
    fi
```
What would I need to change here to not automatically filter out file names that don't start with the completion, like I was able to do before? Thanks

**Comment by coreegor** [comment]
What package did you use when it worked?

**Comment by coreegor** [comment]
In any case, the original code for the autocompletion can be found here https://github.com/pallets/click/blob/main/src/click/shell_completion.py#L93

**Comment by hintron** [comment]
I realized what my problem was: I didn't convert my Click 7.x autocomplete function to the 8.x way of doing it, so my autocomplete function was simply unused.

In case it is helpful for anyone else, here is what I did to implement my "match any part of the script name" autocomplete function:

```Python3
class GetScriptsType(click.ParamType):
    name = "scriptname"

    def shell_complete(self, ctx, param, incomplete):
        """Populate scripts"""
        scripts = list_scripts()
        return [click.shell_completion.CompletionItem(script) for script in scripts if incomplete in script]
```
with
```Python3
@click.argument("script-name", type=GetScriptsType())
```

This will result in e.g.:

```
$ my-prog 5<TAB>
hdf5.py        refresh_h5.sh  update_h5      
```

Closing this out. Thanks!
